### ISSUE TITLE
Proposed SIG-Build meeting agenda for 28/OCT/2021 @ 02:00pm PT / 05:00pm ET

### ISSUE THREAD

**Issue by aFinchy** [o3de/sig-operations#18]
## Meeting Details

- **Date/Time:** 28/OCT/2021 @ 02:00pm PT / 05:00pm ET
- **Location:** [Discord SIG-Operations Voice Room](https://discord.gg/79NRgDuhT4)
- **Moderator:** TBA
- **Note Taker** Volunteers welcome!

The [SIG-Operations Meetings](https://github.com/o3de/sig-operations/tree/main/meetings) repo contains the history past calls, including a link to the agenda, recording, notes, and resources.

## SIG Updates

TBA

## Meeting Agenda

TBA

## Outcomes from Discussion topics

TBA

## Action Items

TBA

## Open Discussion Items

- Automation of Review and Merge management on Github Repos
- Updating the Charter
- RFC Archiving/Updating

Please comment on this for anything you would like added to the agenda!

**Comment by lmbr-pip** [comment]
Closing out old meeting agendas.
