### ISSUE TITLE
Proposed SIG-Ops meeting agenda for November-11-21 2pm PST

### ISSUE THREAD

**Issue by FiniteStateGit** [o3de/sig-operations#26]
## Meeting Details

- **Date/Time:** November 11, 2021 @ 2pm PST
- **Location:** [Discord SIG-Operations Voice Room](https://discord.gg/79NRgDuhT4)
- **Moderator:** TBD
- **Note Taker** Finite_State

## SIG Updates

- [November 4, 2021 Sig-Ops meeting notes](https://github.com/o3de/sig-operations/blob/bf707e34b3ae5ee9c0957f87e169b8b6b158c71c/meetings/notes/sig-operations-20211104)
- [October 21, 2021 Sig-Ops meeting notes](https://github.com/o3de/sig-operations/blob/5ae64d6e480dff8209a2a834e1e330f5ae63801e/meetings/notes/sig-operations-20211021.md)

## Meeting Agenda

- Status report on Discord streaming issue.
- Review open discussion items.
- Any additional proposed topics.

## Outcomes from Discussion topics

[Charter update discussion](#23)

## Action Items

Action Items for SIG maintainers:

**Open PRs to merge**
- #19  
- #20
- #21 
- #25 

## Open Discussion Items

**Charter Updates**
SIG Charter as its mostly empty in this repro. This makes it hard to understand what is the ownership and responsibilities of sig-operations. Propose we start the process of updating sig-operations charter.

**Website Ownership**
Ownership of the o3de.org website and if sig-operations is responsible for any pieces. This is cross-cutting from sig-security about who is responsible for the security and frameworks used to host content.

**RFC Archiving**
Process for RFC archiving, if a responsibility for sig-operations or a process for sig-operations to own (due to lack of charter unclear if operations is responsible SIG for this). Problem: most SIGs are archiving RFCs locally in their repros which makes discovery hard. RFCs are also not being archived consistently. What processes should we be following? What should we be doing with https://github.com/o3de/rfcs? What should be the communication policy when RFCs are published, moved to final comment and accepted by a SIG?

**Automation of review and merge management on Github repos**
c/o @Stramer

We have a problem with community reviewing that's currently seriously affecting docs and will affect engineering eventually. Infrastructure issue with GitHub, caused between https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews (PRs with required write/admin reviewers) and https://docs.github.com/en/organizations/organizing-members-into-teams/managing-code-review-assignment-for-your-team (round-robin assignment by org team). Codeowners must have WRITE permissions (https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) which we cannot give to community memebers.

Summary:

Nobody who is a community reviewer can ever be auto-assigned, which is debatably an issue.
Nobody who is a community reviewer can get a green check to approve merge, meaning 2 write/admin privs MUST green check to pass.

**Abandoned issues**
Community member wondered if we should be autoclosing abandoned issues in GitHub, as with other open source projects?

**Sig maintainers**
Propose some maintainers for the SIG as none exist it seems.

**Comment by FiniteStateGit** [comment]
Suggestion for agenda item: 

There is no sig/operations tag for the o3de or o3de.org repos.  Do we need one?

**Comment by tonybalandiuk** [comment]
Suggestion for Agenda Item:
There has been some confusion as to the purpose of this SIG as defined at https://github.com/o3de/sig-operations/discussions/23  .  Specifically, there has been question whether this sig owns defining processes in general or if the scope is limited to automation (which is as it is currently stated). Maybe the name is confusing - perhaps it should be "SIG-Software-Operations" or maybe "SIG-Tools"? Perhaps my comment here belongs under the Charter discussion itself, but I think it is important to discuss this item this week since it has caused confusion across at least half a dozen people I work with.

**Comment by JustFinchy** [comment]
@FiniteStateGit Can you please close this issue?
