### ISSUE TITLE
Proposed SIG-Operations meeting agenda for December-9-21

### ISSUE THREAD

**Issue by FiniteStateGit** [o3de/sig-operations#30]
## Meeting Details

- **Date/Time:** December 9, 2021 @ 2PM PST
- **Location:** [Discord SIG-Operations Voice Room](https://discord.gg/79NRgDuhT4)
- **Moderator:** lmbr-pip (Pip)
- **Note Taker** Finite_State (Jonathan)

The [SIG-Operations Meetings](https://github.com/o3de/sig-operations/tree/main/meetings) repo contains the history past calls, including a link to the agenda, recording, notes, and resources.

## Meeting Agenda

- Potential issue discovered with Discord audio and video sharing.  Refer to thread `How to improve Discord screen...` in Discord channel #sig-ui-ux.

## Action Items

- Investigate server default streaming settings.
- Request TSC guidance on sig scope. Specifically, whether and in what capacity the sig should address cross-cutting issues.
- Further charter refinements.

Policy for RFC archiving
Policy for abandoned Github issues
Changes to Github autolabeling
DCO-Validation for additional operations
Long-Term credential management

**Automation of review and merge management on Github repos**
c/o @Stramer

We have a problem with community reviewing that's currently seriously affecting docs and will affect engineering eventually. Infrastructure issue with GitHub, caused between https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/approving-a-pull-request-with-required-reviews (PRs with required write/admin reviewers) and https://docs.github.com/en/organizations/organizing-members-into-teams/managing-code-review-assignment-for-your-team (round-robin assignment by org team). Codeowners must have WRITE permissions (https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) which we cannot give to community memebers.

Summary:

Nobody who is a community reviewer can ever be auto-assigned, which is debatably an issue.
Nobody who is a community reviewer can get a green check to approve merge, meaning 2 write/admin privs MUST green check to pass.

**Comment by FiniteStateGit** [comment]
I'd propose we cancel the Nov 25 sig-ops meeting. Next meeting to be held Dec 2.

**Comment by FiniteStateGit** [comment]
c/o Finchy

Community surveys. 
- What types of Content creation is everyone looking for. 
- Public events that piques most people's interests.
- If anyone is able to help design media and content for the engine promotion/advertising.
- etc

**Comment by FiniteStateGit** [comment]
Sig-ops meeting delayed until 12/9 in anticipation of a response from the TSC.

**Comment by FiniteStateGit** [comment]
Adding comment from Discord:

Terry [Amazon]: @sig-operations Hey all, we've just identified something I think that sig-operations can/should own.  When we have someone nominated (and approved) to become a reviewer that is not a member of the org, we need a mechanism for sig chairs and/or co-chairs to be able to get them invited to the o3de org (and added to the reviewer and sig-* group as well).  Due to the permissions required, this seems like a good bot-type solution. 

Terry [Amazon]: In the same vein we'll also eventually need a way for those same people to be able to add people to the maintainer group as well in case it is simple to handle all of this at the same time.

**Comment by JustFinchy** [comment]
Now that we are at Level 3, we are able to stream at a higher FPS

**Comment by JustFinchy** [comment]
@FiniteStateGit Can you please close this issue?
