### ISSUE TITLE
Proposed SIG-Operations meeting agenda for Feb-03-22

### ISSUE THREAD

**Issue by JustFinchy** [o3de/sig-operations#34]
## Meeting Details

- **Date/Time:** Feb. 3rd, 2022 @ 09:00pm UTC / 04:00pm ET
- **Location:** [Discord SIG-Operations Voice Room](https://discord.gg/79NRgDuhT4)
- **Moderator:** @aFinchy
- **Note Taker** TBD
- **Discord Event** https://discord.gg/f3Ah5DGY?event=935653780240875560

## SIG Updates

Current Sig-Ops chair stepped down. 

## Meeting Agenda

Discussion of Previous Agendas. https://github.com/o3de/sig-operations/issues/32 https://github.com/o3de/sig-operations/issues/33

- Ideas, suggestions and chatter around Automation. This would be both Git side as well as Discord side to help fill the gaps that are currently present. (There has been talk about duplicate issues). 
- Possibility of maybe a Ticket in discord for issues to help filter? 

## Outcomes from Discussion topics

- Implementation of various bots
- Automation of tasks that are otherwise required by human
- Easier workflow, less time dealing with duplicate things

## Action Items

Review previous Agenda notes and topics. 

## Open Discussion Items

List any additional items below!

**Comment by sptramer** [comment]
**Proposed item**: Discord migration plan
**Summary**: In the event that we need to switch live discussion hosting off Discord, we should have some kind of migration plan. _Why_ we would migrate matters less than having a recovery plan: How we produce backups, notify users, perform retrospectives on migration activities, etc. Don't expect this to be resolved in the meeting but come up with a list of action items for the SIG.
